# Generated by Django 4.1.7 on 2023-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpId',
            field=models.CharField(max_length=30),
        ),
    ]
