# Generated by Django 4.1.7 on 2023-02-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP', '0002_alter_employee_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpDesignation',
            field=models.CharField(max_length=25),
        ),
    ]
